.TH "btrfs-extent-same" "8" "March 2014" "Version 0.01"
.SH "NAME"
btrfs-extent-same \- directly access the btrfs-extent-same ioctl
.SH "SYNOPSIS"
\fBbtrfs-extent-same\fR \fIextent-len\fI \fIfile1\fI \fIoffset1\fI \fI...\fI
.SH "DESCRIPTION"
.PP
\fBbtrfs-extent-same\fR 
\fIextent-len\fR and all offsets should be specified in bytes.

.SH "SEE ALSO"
.BR filesystems(5)
.BR btrfs(8)
